In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [11]:
np.random.seed(1349) 

n_simulations =100_000

In [ ]:
#How likely is it that you roll doubles when rolling two dice?

In [5]:
n_trials = nrows = 1000000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#print(rolls)

rolls =pd.DataFrame(rolls)
(rolls[0] == rolls[1]).mean()


0.167321

In [1]:
6/36

0.16666666666666666

In [6]:
rolls = pd.DataFrame(rolls)
rolls.head()

0  1
0  2  4
1  3  1
2  6  3
3  3  2
4  3  4

In [8]:
(rolls[0] == rolls[1]).mean()

0.167321

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [9]:
n_coins = 8 
outcomes = ['H', 'T']

In [12]:
coinflips = np.random.choice(outcomes, size=(n_simulations, n_coins))
coinflips

array([['H', 'H', 'T', ..., 'H', 'T', 'T'],
       ['T', 'T', 'T', ..., 'H', 'T', 'T'],
       ['H', 'H', 'T', ..., 'T', 'T', 'H'],
       ...,
       ['T', 'H', 'H', ..., 'H', 'T', 'H'],
       ['T', 'H', 'T', ..., 'T', 'T', 'H'],
       ['H', 'H', 'H', ..., 'H', 'T', 'T']], dtype='<U1')

In [13]:
flips_by_sim = (coinflips == 'H').sum(axis=1)

flips_by_sim

array([5, 2, 4, ..., 6, 4, 6])

Landing on Heads exactly 3 times

In [15]:
(flips_by_sim == 3).mean()

0.21785

In [16]:
(flips_by_sim > 3).mean()

0.63618

In [17]:
outcomes = ['H','T']
n_coins = 8

coinflips = np.random.choice(outcomes, size=(n_simulations, n_coins))
flips_by_sim = (coinflips == 'H').sum(axis=1)
(flips_by_sim > 3).mean()

0.63566

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [18]:
(.25)*(.25)

0.0625

In [19]:
outcomes = ['wd', 'wd', 'wd', 'ds']

n_billboards = 2

billboards = np.random.choice(outcomes, size=(n_simulations, n_billboards))

billboards

array([['ds', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd'],
       ...,
       ['ds', 'wd'],
       ['wd', 'wd'],
       ['wd', 'ds']], dtype='<U2')

In [20]:
outcomes = ['wd','ds']

billboards = np.random.choice(outcomes, size=(n_simulations, n_billboards), 
                p=[0.75, 0.25])
billboards

array([['wd', 'ds'],
       ['ds', 'wd'],
       ['wd', 'ds'],
       ...,
       ['ds', 'wd'],
       ['wd', 'ds'],
       ['wd', 'wd']], dtype='<U2')

In [22]:
(billboards == 'ds').sum(axis=1)

array([1, 1, 1, ..., 1, 1, 0])

In [23]:
prob = ((billboards == 'ds').sum(axis=1) == 2).mean()
prob

0.0626

In [24]:
1-prob

0.9374

In [25]:
odds = prob/(1-prob)
odds

0.06678045658203542

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [26]:
mean = 3 
sd = 1.5

n_days = 5

In [27]:
poptarts_bought_day = np.random.normal(mean, sd, size=(n_simulations, n_days))

poptarts_bought_day


array([[ 4.06727987,  5.42858779, -0.55643656,  3.64726638,  3.48266155],
       [ 3.15033316,  2.44877615,  0.53991188,  2.21276001,  3.77092258],
       [ 4.12864342,  2.06316262,  2.92173551, -0.80131253,  4.46434539],
       ...,
       [ 2.33166328,  1.87465851,  3.44930493,  4.65019605,  2.25299089],
       [ 3.27307033,  3.01835385,  3.91246446,  0.3017343 ,  3.92353314],
       [ 2.09623644,  4.40829847,  3.21341828,  3.1146626 ,  3.06040166]])

In [28]:
poptarts_bought_per_week = poptarts_bought_day.sum(axis=1)

poptarts_bought_per_week

array([16.06935903, 12.12270378, 12.77657442, ..., 14.55881366,
       14.42915608, 15.89301745])

In [29]:
(poptarts_bought_per_week <= 16).mean()

0.61692

In [30]:
men_avg= 178
men_std=8

women_avg=170
women_std=6

In [31]:
height_men = np.random.normal(men_avg, men_std, n_simulations)

height_men

array([177.04695011, 181.97837196, 172.77491682, ..., 181.97012411,
       181.74956493, 171.98323203])

In [32]:
height_women = np.random.normal(women_avg, women_std, n_simulations)

height_men

array([177.04695011, 181.97837196, 172.77491682, ..., 181.97012411,
       181.74956493, 171.98323203])

In [33]:
(height_women > height_men).mean()

0.2113

In [34]:
men = np.random.normal(178, 8, size = n_simulations)
men

array([188.34456878, 174.38861611, 177.9100437 , ..., 179.16793993,
       176.43381907, 189.85788966])

In [35]:
women = np.random.normal(170, 6, size = n_simulations)
women

array([163.25723658, 173.5476916 , 163.84754019, ..., 168.79783119,
       180.73498735, 170.69078238])

In [36]:
(women > men).mean()

0.2119

5. Compare Heights
Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?

In [37]:
men_avg= 178
men_std=8

women_avg=170
women_std=6

In [38]:
height_men = np.random.normal(men_avg, men_std, n_simulations)

height_men

array([192.48444555, 170.71111817, 176.47963871, ..., 179.7477684 ,
       178.09227818, 190.6174004 ])

In [39]:
height_women = np.random.normal(women_avg, women_std, n_simulations)
height_men

array([192.48444555, 170.71111817, 176.47963871, ..., 179.7477684 ,
       178.09227818, 190.6174004 ])

In [40]:
(height_women > height_men).mean()

0.21056

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.
What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
What is the probability that we observe an installation issue within the first 150 students that download anaconda?
How likely is it that 450 students all download anaconda without an issue?

In [41]:
outcomes = ['S', 'F']

n_students = 50

In [42]:
outcomes = ['S', 'F']

n_students = 50

In [43]:
downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [44]:
(downloads == 'S').sum(axis=1)

array([50, 50, 50, ..., 50, 49, 50])

In [45]:
((downloads == 'S').sum(axis=1) == 50).mean()

0.81717

In [46]:
outcomes = ['S', 'F']
n_students = 100

downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])

((downloads == 'S').sum(axis=1) < n_students).mean()

0.33179

In [47]:
outcomes = ['S', 'F']
n_students = 150

downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])

((downloads == 'S').sum(axis=1) < n_students).mean()

0.44941

In [48]:
outcomes = ['S', 'F']
n_students = 450

downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])

((downloads == 'S').sum(axis=1) == n_students).mean()

0.16702

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [49]:
n_days = 3

In [50]:
trucks = np.random.choice([0, 1], size = (n_simulations, n_days), p = [0.3, 0.7])

trucks

array([[0, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 0]])

probability that no truck shows up in 3 days

In [51]:
(trucks.sum(axis = 1) == 0).mean()

0.02733

How likely is it that a food truck will show up sometime this week


In [52]:
(trucks.sum(axis = 1) >= 1).mean()

0.97267